const recipeSchema = [
  {  "id": 1,
    "dishName": "Margherita Pizza",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Margherita Pizza food",
    "cuisine": "Italian",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 317,
    "rating": 4.1,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Margherita Pizza",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 2,
    "dishName": "Chicken Biryani",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Chicken Biryani food",
    "cuisine": "Indian",
    "category": "Lunch",
    "type": "Non-Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 334,
    "rating": 4.2,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Chicken Biryani",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 3,
    "dishName": "Butter Chicken",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Butter Chicken food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 351,
    "rating": 4.3,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Butter Chicken",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 4,
    "dishName": "Paneer Butter Masala",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Paneer Butter Masala food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 368,
    "rating": 4.4,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Paneer Butter Masala",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 5,
    "dishName": "Veg Fried Rice",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Veg Fried Rice food",
    "cuisine": "Chinese",
    "category": "Lunch",
    "type": "Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 385,
    "rating": 4.5,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Veg Fried Rice",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 6,
    "dishName": "Hakka Noodles",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Hakka Noodles food",
    "cuisine": "Chinese",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 402,
    "rating": 4.6,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Hakka Noodles",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 7,
    "dishName": "Chole Bhature",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Chole Bhature food",
    "cuisine": "Indian",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 419,
    "rating": 4.7,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Chole Bhature",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 8,
    "dishName": "Rajma Chawal",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Rajma Chawal food",
    "cuisine": "Indian",
    "category": "Lunch",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 436,
    "rating": 4.8,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Rajma Chawal",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 9,
    "dishName": "Dal Tadka",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Dal Tadka food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 453,
    "rating": 4.9,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Dal Tadka",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 10,
    "dishName": "Masala Dosa",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Masala Dosa food",
    "cuisine": "South Indian",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 470,
    "rating": 4.0,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Masala Dosa",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 11,
    "dishName": "Idli Sambar",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Idli Sambar food",
    "cuisine": "South Indian",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 487,
    "rating": 4.1,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Idli Sambar",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 12,
    "dishName": "Pav Bhaji",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Pav Bhaji food",
    "cuisine": "Indian",
    "category": "Snacks",
    "type": "Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 504,
    "rating": 4.2,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Pav Bhaji",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 13,
    "dishName": "Pani Puri",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Pani Puri food",
    "cuisine": "Indian",
    "category": "Snacks",
    "type": "Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 521,
    "rating": 4.3,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Pani Puri",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 14,
    "dishName": "Aloo Paratha",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Aloo Paratha food",
    "cuisine": "Indian",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 538,
    "rating": 4.4,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Aloo Paratha",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 15,
    "dishName": "Palak Paneer",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Palak Paneer food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 555,
    "rating": 4.5,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Palak Paneer",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 16,
    "dishName": "Chicken Curry",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Chicken Curry food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 572,
    "rating": 4.6,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Chicken Curry",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 17,
    "dishName": "Fish Curry",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Fish Curry food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 589,
    "rating": 4.7,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Fish Curry",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 18,
    "dishName": "Mutton Rogan Josh",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Mutton Rogan Josh food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 606,
    "rating": 4.8,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Mutton Rogan Josh",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 19,
    "dishName": "Egg Curry",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Egg Curry food",
    "cuisine": "Indian",
    "category": "Lunch",
    "type": "Non-Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 623,
    "rating": 4.9,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Egg Curry",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 20,
    "dishName": "Veg Pulao",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Veg Pulao food",
    "cuisine": "Indian",
    "category": "Lunch",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 640,
    "rating": 4.0,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Veg Pulao",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 21,
    "dishName": "Tandoori Chicken",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Tandoori Chicken food",
    "cuisine": "Indian",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 657,
    "rating": 4.1,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Tandoori Chicken",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 22,
    "dishName": "Chicken Tikka",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Chicken Tikka food",
    "cuisine": "Indian",
    "category": "Snacks",
    "type": "Non-Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 674,
    "rating": 4.2,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Chicken Tikka",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 23,
    "dishName": "Grilled Sandwich",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Grilled Sandwich food",
    "cuisine": "American",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 691,
    "rating": 4.3,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Grilled Sandwich",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 24,
    "dishName": "Veg Burger",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Veg Burger food",
    "cuisine": "American",
    "category": "Lunch",
    "type": "Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 708,
    "rating": 4.4,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Veg Burger",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 25,
    "dishName": "Cheeseburger",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Cheeseburger food",
    "cuisine": "American",
    "category": "Lunch",
    "type": "Non-Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 725,
    "rating": 4.5,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Cheeseburger",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 26,
    "dishName": "French Fries",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "French Fries food",
    "cuisine": "American",
    "category": "Snacks",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 742,
    "rating": 4.6,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for French Fries",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 27,
    "dishName": "Caesar Salad",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Caesar Salad food",
    "cuisine": "Italian",
    "category": "Lunch",
    "type": "Non-Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 309,
    "rating": 4.7,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Caesar Salad",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 28,
    "dishName": "Greek Salad",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Greek Salad food",
    "cuisine": "Greek",
    "category": "Lunch",
    "type": "Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 326,
    "rating": 4.8,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Greek Salad",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 29,
    "dishName": "Pasta Alfredo",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Pasta Alfredo food",
    "cuisine": "Italian",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 343,
    "rating": 4.9,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Pasta Alfredo",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 30,
    "dishName": "Pasta Arrabbiata",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Pasta Arrabbiata food",
    "cuisine": "Italian",
    "category": "Dinner",
    "type": "Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 360,
    "rating": 4.0,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Pasta Arrabbiata",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 31,
    "dishName": "Lasagna",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Lasagna food",
    "cuisine": "Italian",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 377,
    "rating": 4.1,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Lasagna",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 32,
    "dishName": "Mushroom Soup",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Mushroom Soup food",
    "cuisine": "International",
    "category": "Starter",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 394,
    "rating": 4.2,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Mushroom Soup",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 33,
    "dishName": "Tomato Soup",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Tomato Soup food",
    "cuisine": "International",
    "category": "Starter",
    "type": "Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 411,
    "rating": 4.3,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Tomato Soup",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 34,
    "dishName": "Chocolate Cake",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Chocolate Cake food",
    "cuisine": "International",
    "category": "Dessert",
    "type": "Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 428,
    "rating": 4.4,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Chocolate Cake",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 35,
    "dishName": "Brownies",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Brownies food",
    "cuisine": "International",
    "category": "Dessert",
    "type": "Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 445,
    "rating": 4.5,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Brownies",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 36,
    "dishName": "Pancakes",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Pancakes food",
    "cuisine": "American",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 462,
    "rating": 4.6,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Pancakes",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 37,
    "dishName": "Waffles",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Waffles food",
    "cuisine": "Belgian",
    "category": "Breakfast",
    "type": "Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 479,
    "rating": 4.7,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Waffles",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 38,
    "dishName": "Ice Cream Sundae",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Ice Cream Sundae food",
    "cuisine": "International",
    "category": "Dessert",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 496,
    "rating": 4.8,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Ice Cream Sundae",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 39,
    "dishName": "Mango Smoothie",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Mango Smoothie food",
    "cuisine": "International",
    "category": "Beverage",
    "type": "Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 513,
    "rating": 4.9,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Mango Smoothie",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 40,
    "dishName": "Strawberry Milkshake",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Strawberry Milkshake food",
    "cuisine": "International",
    "category": "Beverage",
    "type": "Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 530,
    "rating": 4.0,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Strawberry Milkshake",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 41,
    "dishName": "Oreo Shake",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Oreo Shake food",
    "cuisine": "International",
    "category": "Beverage",
    "type": "Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 547,
    "rating": 4.1,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Oreo Shake",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 42,
    "dishName": "Lemonade",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Lemonade food",
    "cuisine": "International",
    "category": "Beverage",
    "type": "Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 564,
    "rating": 4.2,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Lemonade",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 43,
    "dishName": "Hot Chocolate",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Hot Chocolate food",
    "cuisine": "International",
    "category": "Beverage",
    "type": "Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 581,
    "rating": 4.3,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Hot Chocolate",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 44,
    "dishName": "Samosa",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Samosa food",
    "cuisine": "Indian",
    "category": "Snacks",
    "type": "Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 598,
    "rating": 4.4,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Samosa",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 45,
    "dishName": "Spring Rolls",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Spring Rolls food",
    "cuisine": "Chinese",
    "category": "Snacks",
    "type": "Veg",
    "cookTime": "50 mins",
    "difficulty": "Easy",
    "calories": 615,
    "rating": 4.5,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Spring Rolls",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 46,
    "dishName": "Momos",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Momos food",
    "cuisine": "Tibetan",
    "category": "Snacks",
    "type": "Veg",
    "cookTime": "60 mins",
    "difficulty": "Medium",
    "calories": 632,
    "rating": 4.6,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Momos",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 47,
    "dishName": "Sushi Roll",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Sushi Roll food",
    "cuisine": "Japanese",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "70 mins",
    "difficulty": "Hard",
    "calories": 649,
    "rating": 4.7,
    "servings": 5,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Sushi Roll",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 48,
    "dishName": "Tacos",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Tacos food",
    "cuisine": "Mexican",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "20 mins",
    "difficulty": "Easy",
    "calories": 666,
    "rating": 4.8,
    "servings": 2,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Tacos",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 49,
    "dishName": "Burrito",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Burrito food",
    "cuisine": "Mexican",
    "category": "Lunch",
    "type": "Non-Veg",
    "cookTime": "30 mins",
    "difficulty": "Medium",
    "calories": 683,
    "rating": 4.9,
    "servings": 3,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Burrito",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
    ]
  },
  {
    "id": 50,
    "dishName": "Ramen",
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    "imageSearchHint": "Ramen food",
    "cuisine": "Japanese",
    "category": "Dinner",
    "type": "Non-Veg",
    "cookTime": "40 mins",
    "difficulty": "Hard",
    "calories": 700,
    "rating": 4.0,
    "servings": 4,
    "ingredients": [
      "2 tbsp oil",
      "1 onion (chopped)",
      "2 cloves garlic",
      "1 tsp ginger",
      "Salt to taste",
      "Black pepper",
      "Main ingredient for Ramen",
      "Fresh herbs for garnish"
    ],
    "instructions": [
      "Prepare all ingredients.",
      "Heat oil in a pan.",
      "Saute onion, garlic, and ginger.",
      "Add the main ingredients and seasonings.",
      "Cook until fully done, stirring occasionally.",
      "Taste and adjust seasoning.",
      "Garnish and serve hot."
]}
]

module.exports = { recipe: recipeSchema};